---

- name: Getting sources
  git: >
    repo=https://github.com/nicolasff/phpredis.git
    dest=/usr/local/src/phpredis
  tags:
    - web
    - php5-redis
    - install

- name: Make clean
  shell: >
    phpize && ./configure && make && make install
    chdir=/usr/local/src/phpredis
    creates=/usr/lib/php5/20100525/redis.so
  tags:
    - web
    - php5-redis
    - install
